### ISSUE TITLE
Templates do not properly locate each other when using file compiler with remote compiler

### ISSUE THREAD

**Issue by nicholashagen** [teatrove/teatrove#41]
When using part of the template path as remote paths and the other half as local templates via file paths, templates do not always cross communicate and properly resolve

**Comment by jflo** [comment]
+1 because we are trying to bundle our releases as a single artifact but still allow for emergency overrides via http paths prepended to the template path.

**Comment by nicholashagen** [comment]
what about precompiling templates as part of the release and then using the HTTP paths to override te precompiled templates.  That should work in legacy versions of Tea as well as in TeaTrove.  Regardless, there is a clear issue here dealing with the fact that the various compilers are independent of each other.  Looking to resolve that in 4.1.3.

**Comment by jflo** [comment]
Went down that road already, and could never get the precompiler maven plugin working with our GoPub dependencies. Crazy class loader nightmares.

**Comment by jflo** [comment]
Issue closed... so this is fixed as of 4.1.3 ?

**Comment by nicholashagen** [comment]
Yes and hopefully being released soon. Already committee to master. 

Nicholas Hagen
