### ISSUE TITLE
Release builds to Maven central

### ISSUE THREAD

**Issue by nicholashagen** [teatrove/teatrove#7]
Release generics branch (4.0.x) and operators branch (4.1.x) to Maven central

**Comment by jaxzin** [comment]
We have a Sonatype OSSH repo ready for releases, including SNAPSHOTs if we want to test.

https://issues.sonatype.org/browse/OSSRH-2711

**Comment by jaxzin** [comment]
Do we still want to release both a 4.0 and 4.1 version?

**Comment by nicholashagen** [comment]
Just 4.1. I'm working towards a 4.2 with some of the features I'm adding though. If we are ready to release in Maven central, what do you think of releasing as 4.1 and creating a 4.1 branch to make bug fixes on in the interim as 4.1.x releases. Any new additions or improvements would go on master as a 4.2-SNAPSHOT, such as my template viewer port and improved jmx console. 

Nicholas Hagen
www.znetdevelopment.com/blogs
- sent from my iPhone *

**Comment by jaxzin** [comment]
I'm all for that idea. I create Milestones so if you can associate tickets
with releases if you want.

I'll work on a 4.1 release. Do you want the first release to be 4.1 or
 would you prefer it be 4.1.1 (or even 4.1.2) to reflect what we've already
released privately?

On Thu, Mar 15, 2012 at 9:46 PM, Nicholas Hagen <
reply@reply.github.com

**Comment by nicholashagen** [comment]
Let's do 4.1.2. 

Nicholas Hagen
www.znetdevelopment.com/blogs
- sent from my iPhone *

**Comment by jaxzin** [comment]
[4.1.2 has been released to the Sonatype OSSH Repository](https://oss.sonatype.org/index.html#nexus-search;gav~org.teatrove~~4.1.2~~)

We are waiting for a [one-time enabling of syncing to Central](https://issues.sonatype.org/browse/OSSRH-2711?focusedCommentId=154027#comment-154027). Future releases will not have this manual sign-off.

I have documented [the steps I took to perform the release](https://github.com/teatrove/teatrove/wiki/Releasing-TeaTrove).

**Comment by jaxzin** [comment]
I also created a 4.1 branch that starts at the teatrove-4.1.2 tag.

**Comment by jaxzin** [comment]
Version 4.1.2 is now available in Maven Central! http://bit.ly/y3PjT6
